name: Deploy Application Front OCI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Create .env.production
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" > .env.production
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
          echo "NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}" >> .env.production
          echo "NEXT_PUBLIC_API_URL=${{ secrets.API_URL }}" >> .env.production
          echo "NODE_ENV=production" >> .env.production

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:dev
        
      - name: Run Lint
        run: npm run lint

      - name: Build Application
        run: npm run build:prod

      - name: Login to Docker Hub
        run: docker login -u brazf -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t brazf/estoque-frontend .
          docker push brazf/estoque-frontend

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Call Portainer Webhook
        run: |
          curl -X POST "${{ secrets.WEBHOOK_SECRET }}" || echo "Webhook triggered"

